### PR TITLE
.editorconfig + elegant indentation

### PR DESCRIPTION
**Pull request by marceloboeira**
Both, sublime/atom and github rather work with `.editorconfig` file so it can adjust the source file's indentation patterns of each project separately.

Checkout: http://editorconfig.org

### CODE REVIEW

**Comment by thebergamo** [comment]
My bad! Thanks @marceloboeira on my Sublime the indentation are fine, but I only see now in github how my code are "ugly". 

Thanks very much =D

**Comment by marceloboeira** [comment]
@thebergamo that's why open-source is awesome, I'm happy to help. 
Checkout this link: https://css-tricks.com/changing-spaces-tabs-sublime-text/

I really like the project's ideia, if you could prioritize the demands, I would be help to code something.

**Comment by thebergamo** [comment]
Its a very useful link. I'm glad for that.

I'm and @greenboxal desing this module inspired by CanCan from Ruby. 

You're welcome to contribute and encourage. If you implement this on any project please tell us =D

**Comment by marceloboeira** [comment]
@thebergamo I really like CanCan, I'm going to use it on a Sails Framework project, anytime soon.

**Comment by thebergamo** [comment]
(Is just personal, but I really like the Kraken instead Sails)
Before this project I don't ever earn about CanCan but, now I know this is awesome and I think, this project can help many other developers to integrate a simple and consistent ACL on you own projects.

**Comment by marceloboeira** [comment]
@thebergamo I'm trying to create a Brazilian Sails community, so is just example project, I'm one of the contributors on translating the sails docs and stuff. -> https://github.com/SailsBR/

**Comment by thebergamo** [comment]
Its very nice!! I fork this project an I'll try help to translate the docs.

**Pull request merged**
